baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"


[taxonomies]
  category = "categories"
  audioformat = "audioformats"

[outputs]
  home = ["RSS","mp4"]
  section = ["RSS","mp4"]
  taxonomyTerm = ["RSS","mp4"]
  taxonomy =["RSS","mp4"]

[outputFormats]
[outputFormats.mp4]
mediaType = "application/rss+xml"
baseName = "mp4"