baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"


[taxonomies]
  category = "categories"
  audioformat = "audioformats"

[outputs]
  home = ["RSS"]
  section = ["RSS"]
  taxonomyTerm = ["RSS"]
  taxonomy =["RSS"]
